title:               Nick's Blog
description:         'A record of things I want to remember.'
url:                 http://www.nickbdyer.uk
baseurl:             ''
paginate:            5

author:
  name:              Nick Dyer
  url:               https://twitter.com/nickbdyer
  email:             ndyer@8thlight.com

gems:                [jekyll-paginate]
permalink:           pretty

github:              'http://www.github.com/nickbdyer'
twitter:             'http://www.twitter.com/nickbdyer'

